import React from 'react';
import {Link} from 'react-router-dom'

function Landing(props) {

  return (
    <div>
      <div>
        <h1>Share it... Don't Waste it</h1>
        <li>
          <Link>Have Food</Link>
        </li>
        <li>
          <Link>Need Food</Link>
        </li>
      </div>
      <div>
        <h2>Leftovers was created to Fight Food Waste</h2>

        <h3>Some Food for Thought ...</h3>
        <li>The United States discards 80 billion pounds of ediable food every year</li>
        <li>While 35 million people across America has food insecurity. That number is expected to rise to as much as 50 million in 2021</li>
        <li>Wasting food contributes to 11 percent of the world's greenhouse gas emissions</li>
      </div>
      <div>
        <p>"hand with heart/food" icon goes here</p>
        <h3>Share your leftovers with others</h3>
        <p>12.8 percent of New Yorkers are food insecure</p>
      </div>
      <div>
        <p>"carrot" Icon goes here</p>
        <h3>Track your leftover foods</h3>
        <p>The Natural Resources Defense Council (NRDC) found that 68 percent of all discarded food was considered still edible.</p>
        <p>54 percent of food waste was generated in residential settings, while 20 percent were generated by restaurants and caterers</p>
      </div>
      <div>
        <h3>Contact Us</h3>
        <p>our emails and shit</p>
      </div>
      <div>
        <h3>Resources: More info </h3>
        <p>More info</p>
      </div>
    </div>
  );
}

export default Landing;